//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fit
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class fit3Entities : DbContext
    {

        public fit3Entities()
            : base("name=fit3Entities")
        {
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Kvitancya> Kvitancyas { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<Usluga> Uslugas { get; set; }
    }
}
