//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usluga
    {
        public Usluga()
        {
            this.Kvitancyas = new HashSet<Kvitancya>();
        }
    
        public int Id { get; set; }
        public string Nazvanie { get; set; }
        public int Stoimost { get; set; }
    
        public virtual ICollection<Kvitancya> Kvitancyas { get; set; }
    }
}
